# cargo-deny configuration
# https://embarkstudios.github.io/cargo-deny/

[bans]
# Lint level for when multiple versions of the same crate are detected
multiple-versions = "warn"

# List of explicitly disallowed crates
deny = [
    # We want to be runtime-agnostic in library crates
    # This will be overridden in crate-specific deny.toml files
]

# Skip certain crates when checking for duplicates
skip = []

# Similarly named crates that are allowed to coexist
allow = []

[licenses]
# List of explicitly allowed licenses
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016",
]

# Confidence threshold for license detection
confidence-threshold = 0.8

[sources]
# Lint level for what to happen when a crate from a git repository is used
git = "allow"
# Lint level for what to happen when an org is not in the allow list
unknown-registry = "warn"

# A list of advisory IDs to ignore
[advisories]
ignore = []