version: "1.0"
name: "Environment Resolution Test"

networks:
  local:
    type: local

services:
  postgres:
    type: docker
    network: local
    image: postgres:15
    ports:
      - 5432
    env:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "${DB_PASSWORD:-secret}"
      POSTGRES_DB: "testdb"
    health_check:
      tcp:
        port: 5432
      interval: 5
      retries: 3
      timeout: 2

  api:
    type: process
    network: local
    binary: api-server
    dependencies:
      - postgres
    env:
      DATABASE_URL: "postgresql://${DB_USER:-admin}:${DB_PASSWORD:-secret}@${postgres.ip}:${postgres.port}/testdb"
      API_HOST: "${API_HOST:-0.0.0.0}"
      API_PORT: "${API_PORT:-8080}"
    health_check:
      http: "http://localhost:${API_PORT:-8080}/health"
      interval: 10
      retries: 5
      timeout: 3