services:
  integration-tests-dind:
    build:
      context: .
      dockerfile: Dockerfile
    # Need privileged mode for running dockerd
    privileged: true
    environment:
      # Docker daemon config
      DOCKER_TLS_CERTDIR: ""
      # Pass through environment variables for tests
      RUST_LOG: ${RUST_LOG:-info}
      RUST_BACKTRACE: ${RUST_BACKTRACE:-1}
    volumes:
      # Mount the entire project
      - ../..:/workspace
      # Mount local-network directory (if it exists)
      - ${LOCAL_NETWORK_PATH:-./empty}:/local-network:ro
      # Docker data volume for DinD
      - dind-docker-data:/var/lib/docker
      # Mount host's Docker socket for image access (read-only)
      - /var/run/docker.sock:/var/run/docker-host.sock:ro
      # Mount cargo cache for faster builds
      - cargo-cache:/usr/local/cargo/registry
      - cargo-git:/usr/local/cargo/git
      # Mount logs directory directly to host for easy access
      - ../test-activity:/workspace/test-activity
    # No port mappings needed - services run inside DinD
    working_dir: /workspace

volumes:
  dind-docker-data:
  cargo-cache:
  cargo-git: