//! Test crate for harness-macros
//!
//! This crate exists solely to test the proc macros from harness-macros,
//! since proc macros cannot be tested in the same crate where they're defined.

#![cfg(test)]

use async_trait::async_trait;
use harness_core::action::{JsonAction, JsonActionRegistry, ServiceJsonActions};
use harness_core::{
    service::{Service, ServiceEvents},
    Error,
};
use harness_macros::{json_action, json_actions};
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
use std::result::Result;

/// A simple test service to verify macro generation
pub struct TestService {
    value: i32,
    event_tx: async_channel::Sender<TestEvent>,
    event_rx: async_channel::Receiver<TestEvent>,
}

#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
pub struct TestEvent {
    message: String,
}

#[json_actions]
impl TestService {
    pub fn new() -> Self {
        let (tx, rx) = async_channel::unbounded();
        Self {
            value: 42,
            event_tx: tx,
            event_rx: rx,
        }
    }

    #[json_action]
    pub async fn add(&self, amount: i32) -> Result<i32, Error> {
        let result = self.value + amount;
        let _ = self
            .event_tx
            .send(TestEvent {
                message: format!("Added {}, result: {}", amount, result),
            })
            .await;
        Ok(result)
    }

    #[json_action]
    pub async fn multiply(&self, factor: i32) -> Result<i32, Error> {
        Ok(self.value * factor)
    }

    #[json_action]
    pub async fn get_value(&self) -> Result<i32, Error> {
        Ok(self.value)
    }

    // This method should not get a generated action
    pub fn internal_method(&self) -> i32 {
        self.value
    }
}

impl Service for TestService {
    fn service_type() -> &'static str {
        "test"
    }

    fn name(&self) -> &str {
        "test-service"
    }

    fn description(&self) -> &str {
        "A test service for macro verification"
    }
}

#[async_trait]
impl ServiceEvents for TestService {
    type Event = TestEvent;

    fn event_stream(&self) -> async_channel::Receiver<Self::Event> {
        self.event_rx.clone()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[smol_potat::test]
    async fn test_dispatch_json_action() {
        let service = TestService::new();

        // Test dispatching add action via JSON
        let input = serde_json::json!({ "amount": 15 });
        let result = service.dispatch_json_action("add", input).await.unwrap();
        assert_eq!(result, 57); // 42 + 15

        // Test dispatching multiply action via JSON
        let input = serde_json::json!({ "factor": 2 });
        let result = service
            .dispatch_json_action("multiply", input)
            .await
            .unwrap();
        assert_eq!(result, 84); // 42 * 2

        // Test dispatching get_value action via JSON (empty input)
        let result = service
            .dispatch_json_action("get_value", serde_json::json!({}))
            .await
            .unwrap();
        assert_eq!(result, 42);

        // Test unknown action
        let result = service
            .dispatch_json_action("unknown", serde_json::json!({}))
            .await;
        assert!(result.is_err());
    }

    #[test]
    fn test_generated_action_structs_exist() {
        // These structs should be generated by the macro
        let _add = AddAction { amount: 5 };
        let _multiply = MultiplyAction { factor: 2 };
        let _get_value = GetValueAction {};
    }

    #[test]
    fn test_action_names() {
        assert_eq!(AddAction::action_name(), "add");
        assert_eq!(MultiplyAction::action_name(), "multiply");
        assert_eq!(GetValueAction::action_name(), "get_value");
    }

    #[test]
    fn test_service_registration() {
        let mut registry = JsonActionRegistry::new();
        TestService::register_actions(&mut registry).unwrap();

        let action_names = registry.action_names();
        assert!(action_names.contains(&"add".to_string()));
        assert!(action_names.contains(&"multiply".to_string()));
        assert!(action_names.contains(&"get_value".to_string()));
    }

    #[smol_potat::test]
    async fn test_action_execution() {
        let service = TestService::new();

        // Test add action
        let add_action = AddAction { amount: 10 };
        let result = add_action.execute(&service).await.unwrap();
        assert_eq!(result, 52); // 42 + 10

        // Test multiply action
        let multiply_action = MultiplyAction { factor: 3 };
        let result = multiply_action.execute(&service).await.unwrap();
        assert_eq!(result, 126); // 42 * 3

        // Test get_value action
        let get_action = GetValueAction {};
        let result = get_action.execute(&service).await.unwrap();
        assert_eq!(result, 42);
    }

    #[smol_potat::test]
    async fn test_event_emission() {
        let service = TestService::new();

        // Execute add action which emits an event
        let add_action = AddAction { amount: 10 };
        let _ = add_action.execute(&service).await.unwrap();

        // Check that event was emitted
        let event = service.event_stream().recv().await.unwrap();
        assert_eq!(event.message, "Added 10, result: 52");
    }

    #[test]
    fn test_action_serialization() {
        let action = AddAction { amount: 25 };
        let json = serde_json::to_string(&action).unwrap();
        assert_eq!(json, r#"{"amount":25}"#);

        let deserialized: AddAction = serde_json::from_str(&json).unwrap();
        assert_eq!(deserialized.amount, 25);
    }
}
