//! JSON action trait for WebSocket/JSON API boundary
//!
//! JsonActions are types that bridge the gap between JSON messages
//! and strongly-typed service methods. They are used exclusively
//! for the wire protocol, not for internal Rust-to-Rust calls.

use async_trait::async_trait;
use schemars::JsonSchema;
use serde::Serialize;
use serde::de::DeserializeOwned;
use std::collections::HashMap;

use crate::Error;
use std::result::Result;

/// Trait for JSON-serializable actions that can be dispatched over the wire
///
/// This trait bridges the gap between JSON messages and strongly-typed service methods.
/// It's not meant for direct Rust-to-Rust calls, only for the WebSocket/JSON API.
///
/// Implementations are typically generated by the `#[json_actions]` macro.
#[async_trait]
pub trait JsonAction<S>: DeserializeOwned + Serialize + JsonSchema + Send + Sized {
    /// The response type returned by this action
    type Response: Serialize + JsonSchema + Send;

    /// The name of this action for JSON routing
    fn action_name() -> &'static str;

    /// Execute this action against the given service
    async fn execute(self, service: &S) -> Result<Self::Response, Error>;
}

/// Registry for JsonAction types for a specific service
///
/// This is a simplified registry that just tracks action names.
/// The actual dispatch will be handled by generated code.
pub struct JsonActionRegistry {
    action_names: Vec<String>,
    action_schemas: HashMap<String, (serde_json::Value, serde_json::Value)>,
}

impl JsonActionRegistry {
    /// Create a new empty registry
    pub fn new() -> Self {
        Self {
            action_names: Vec::new(),
            action_schemas: HashMap::new(),
        }
    }

    /// Register a JsonAction type
    pub fn register<A, S>(&mut self) -> Result<(), Error>
    where
        A: JsonAction<S> + 'static,
        S: 'static,
    {
        let name = A::action_name().to_string();

        if self.action_names.contains(&name) {
            return Err(Error::service_type(format!(
                "Action '{}' already registered",
                name
            )));
        }

        // Generate and store schemas
        let input_schema =
            serde_json::to_value(schemars::schema_for!(A)).unwrap_or(serde_json::Value::Null);
        let response_schema = serde_json::to_value(schemars::schema_for!(A::Response))
            .unwrap_or(serde_json::Value::Null);

        self.action_names.push(name.clone());
        self.action_schemas
            .insert(name, (input_schema, response_schema));

        Ok(())
    }

    /// Get all registered action names
    pub fn action_names(&self) -> &[String] {
        &self.action_names
    }

    /// Get the schema for a specific action
    pub fn get_schema(&self, action_name: &str) -> Option<&(serde_json::Value, serde_json::Value)> {
        self.action_schemas.get(action_name)
    }
}

impl Default for JsonActionRegistry {
    fn default() -> Self {
        Self::new()
    }
}

/// Trait for services that can register their JSON actions
///
/// This is typically implemented by the `#[json_actions]` macro.
pub trait ServiceJsonActions {
    /// Register all JSON actions this service supports
    fn register_actions(registry: &mut JsonActionRegistry) -> Result<(), Error>;
}
